### ISSUE TITLE
[Question] support metrics of different frequency 

### ISSUE THREAD

**Issue by weidezhang** [databrickslabs/tempo#113]
Hi, 
This is a great work. I'm interested in delta lake to store time series data. I'm working in Autonomous Driving field. Currently we are using Ros Bag and store it in S3 bucket from each data collection. 

The characteristic of autonomous driving data is data emitted from different devices (say from different sensors on the car) have different frequencies. Some are 100HZ while other's are 10HZ.  Usually for analytics, we have need to find all the data belong to one specific collection.  

My question is if we store timestamp in milliseconds level, will that be an issue ? Any suggestions on how many delta table need to be created ? 
Further I'm interested in analytics performance if we store billions or even trillions of rows from all the collections into delta lake ？ What will be recommended way to do that in order to achieve best performance ? 

Thanks a lot, 

Weide

**Comment by rportilla-databricks** [comment]
Storing timestamp in milliseconds is absolutely fine. The data layout for the delta table will depend on data size and schema. For example, if you have 1 PB of data, a date field, and the timestamp can be any frequency, then a date partition with a ZORDER on the event type might be the best option. This would be 1 Delta Lake table. But if you have different schemas, then you might want a different Delta table per schema. 

You can store trillions/billions of records - these are good data sizes for Delta Lake tables. I'm happy to chat about this specific use case. DM me here - https://www.linkedin.com/in/ricardo-portilla-a51b6a19/

**Comment by tnixon** [comment]
@bendoan-db could this example be solved with resampling?

**Comment by bendoan-db** [comment]
Closing as this question has been answered.
