### ISSUE TITLE
Typo in interpolation code

### ISSUE THREAD

**Issue by tlinkin** [databrickslabs/tempo#136]
`event_ts` is hardcoded here

https://github.com/databrickslabs/tempo/blob/92137971eb561d361d687d8dc7ee404830770257/python/tempo/interpol.py#L303-L313

But later it is requested as `f"{ts_col}_{target_col}"`

https://github.com/databrickslabs/tempo/blob/92137971eb561d361d687d8dc7ee404830770257/python/tempo/interpol.py#L357-L364

This results in a error if the ts_col is different from `event_ts` such as:

`AnalysisException: cannot resolve 'timestamp2_value' given input columns: [meta.asset_property_name, event_ts_value, next_timestamp, previous_timestamp, timestamp2, value];
`

**Comment by rportilla-databricks** [comment]
Thanks @tlinkin , we are looking into this.

**Comment by guanjieshen** [comment]
Thanks @tlinkin for catching that. Looking to have this resolved in https://github.com/databrickslabs/tempo/pull/139

**Comment by rportilla-databricks** [comment]
@tlinkin , let me know if this is resolved for you and we'll close this.

**Comment by tlinkin** [comment]
yes it is resolved in version 1.5.
We tested and it works as expected !

Thanks
