### ISSUE TITLE
Support higher resample resample frequency

### ISSUE THREAD

**Issue by epa095** [databrickslabs/tempo#148]
The lowest supported resample frequency unit is seconds. Luckily it *is* possible to use "0.001 seconds " to represent e.g. milliseconds, but that is a bit clunky, so it would be nice if at least miliseconds (and maybe microseconds (and nanoseconds?)) would be supported as units.

**Comment by sim-san** [comment]
I am also interested in this functionality.

I looked at the code (https://github.com/databrickslabs/tempo/blob/master/python/tempo/resample.py#L33) and saw that the following function is used there:

[pyspark.sql.functions.window(timeColumn, windowDuration, slideDuration=None, startTime=None) 
](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.functions.window.html)

> Durations are provided as strings, e.g. ‘1 second’, ‘1 day 12 hours’, ‘2 minutes’. Valid interval strings are ‘week’, ‘day’, ‘hour’, ‘minute’, ‘second’, ‘millisecond’, ‘microsecond’.

Is it possible to support also 'millisecond' and 'microsecond' in the resample function of tempo ?
