### ISSUE TITLE
[Doc] Tempo display function could name conflict with databricks display if imported naively

### ISSUE THREAD

**Issue by CTCC1** [databrickslabs/tempo#177]
Been lurking around and saw the recent sphinx doc updates which is greatly appreciated diretionally!
I noted that there are a bunch of python example codes that look like this:
```
from tempo import *
```
the [display function of tempo](https://github.com/databrickslabs/tempo/blob/master/python/tempo/__init__.py#L2) will name conflict with the databricks notebook's default display function and therefore causes normal spark df display to fail. This created a bunch of confusion in our prd environment b/c the stack trace isn't obvious. So I ended up writing some doc at my place to ask people do
```
import tempo
...
tempo.TSDF(...)
```
or
```
from tempo import TSDF, display as tempo_display
```
So maybe you want to avoid this in your default code example (e.g. [here](https://github.com/databrickslabs/tempo#0-read-in-data))

**Comment by souvik-databricks** [comment]
@CTCC1  did you faced any issue where the display failed. As the overloading was handled by me when I wrote the functionality.
Attaching below a screenshot of the functionality working without any issue.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/98817232/159391892-395cd842-a7a2-41ab-aa2d-22f084fde35b.png">

**Comment by souvik-databricks** [comment]
@CTCC1 For now, I think it would be great if you could add the following key

 `DATABRICKS_RUNTIME_VERSION=DATABRICKS_RUNTIME` into the cluster _**Environment variables**_ 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/98817232/159532533-6218d23d-6054-41ed-b9d5-220cf119b5b3.png">
It should solve your issue for now.

**Comment by souvik-databricks** [comment]
@CTCC1 you can now remove the manual environment variable that you had to add. We have just deployed a fix to the bug.
