### ISSUE TITLE
tempo inside `foreachBatch`

### ISSUE THREAD

**Issue by sim-san** [databrickslabs/tempo#192]
Does it work to use tempo inside a [`foreachBatch`](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.streaming.DataStreamWriter.foreachBatch.html) on structured streaming ?

**Comment by tnixon** [comment]
Hi @sim-san, great question. Technically, it should be possible to convert the `batch_df` to a TSDF and then perform tempo operations within a `foreachBatch` function. However, keep in mind that each micro-batch DataFrame will only have a limited slice of the overall stream, and it won't be able to perform operations on data from previous batches. Perhaps if you describe your use-case in a bit more detail, we could better advise you here.

**Comment by sim-san** [comment]
I receive timeseries data from a vehicle. After each trip a CSV is uploaded which will be handled from Databricks Autoloader.

I want to use tempo to resample the data to a given frequency. My plan is to use the trip column as partition_cols.

**Comment by tnixon** [comment]
@sim-san would you be able to share the code snippet with your `forEachBatch` function and how you invoke the `writeStream`?

**Comment by sim-san** [comment]
```
def resample_write(microBatchDF, batchId):
    ts_col = "logging_timestamp"
    partition_cols = ["logger_trip_counter", "veh_id", "org_id"]
    signal_columns = list(can_columns_map.values()) + list(analog_columns_map.values())

    trip_tsdf = tempo.TSDF(joined_df, ts_col=ts_col, partition_cols =partition_cols)
    trip_tsdf_resampled_sdf = (trip_tsdf
                               .resample(freq='5 ms', func='mean', metricCols=signal_columns)
                               .interpolate(method="ffill", target_cols=signal_columns)
                              )

    resampled_df = trip_tsdf_resampled_sdf.df
    
    (resampled_df.write.
     option("txnVersion", batchId)
     .option("txnAppId", appId)
     .mode("append")
     .saveAsTable('test_customer.timeseries'))
```

```
query = (joined_df
         .writeStream
         .foreachBatch(resample_write)
         .option("checkpointLocation", checkpoint_path)
         .trigger(availableNow=True)
         .start())

query.awaitTermination()
```

Does this code snippets help ?

**Comment by rportilla-databricks** [comment]
@sim-san , we will be supporting streaming for select operations. The first function which will support streaming is the asofJoin. Resample/interpolation will come later and are not scoped for the next couple quarters.
