### ISSUE TITLE
Functions for missing data / up-scaling interpolation

### ISSUE THREAD

**Issue by tnixon** [databrickslabs/tempo#2]
We should have some functions to help interpolate data to both:
- fill in missing data
- up-scaling timeseries to finer scales
  - eg. going from daily to hourly data

We should support interpolation along time axis under different window constraints (forward-backward looking or trailing only). Also perhaps methods that look across series (ie PCA)

**Comment by rportilla-databricks** [comment]
This is done. See release dbl-tempo==0.1.3
