### ISSUE TITLE
Support correlating metrics with overlapping time intervals

### ISSUE THREAD

**Issue by vadivelselvaraj** [databrickslabs/tempo#247]
We need support for correlating metrics that share the same time interval. Please refer the below example.

**Input:**
```
id, start_timestamp, end_timestamp, duration, signal_name, signal_value
1, t1, t4, t4-t1, s1, 0
1, t1, t3, t3-t1, s2, 5
```

**Denormalized Output:**
```
id, start_timestamp, end_timestamp, duration, s1, s2
1, t1, t3, t3-t1, 0, 5
1, t3, t4, t4-t3, 0, null
```
**Output Explanation**
_s1_ & _s2_ signals have overlapping intervals for duration _t1 to t3_ and _s1_ from _t3 to t4_ has a non-overlapping interval.

Helps with queries like _Retrieve all instances when s1 had value 0 and s2 had value 8_.

**Comment by R7L208** [comment]
Hey! @vadivelselvaraj we have created an IntervalsDF class to help with handling interval time series data that will work with normalized & denormalized data. I'm working on the request to identify non-overlapping intervals this week.

So far, I've defined a `disjoint` method to identify the non-overlapping intervals between records of the IntervalsDF. Currently, it's passing 2 out of the ~8 test cases I created to capture common patterns & edge cases for the intervals. I'm hoping to have all tests passing EOW

**Comment by R7L208** [comment]
Have all the tests passing. Cleaning up the code and writing documentation this week

**Comment by EvanstsaiTW** [comment]
Hi @R7L208 
I am playing around with this IntervalsDF API to solve the question as the thread author describes. But it seems like this intervalsDF class still does not have the functionality to address the queries like `Retrieve all instances when s1 had value 0 and s2 had value 8.` Disjoin method call can only find out the overlapped interval, is that correct?

**Comment by R7L208** [comment]
Disjoint will find all overlapping intervals and then separate them into disjoint intervals with no overlap. Once that's done, you can use `toDF()` and `filter()`.

for example

```python
idf = IntervalsDF(df)

idf.disjoint().toDF().filter("s1 = 0 and s2 = 8")

```
