### ISSUE TITLE
asof join partition column

### ISSUE THREAD

**Issue by marsupialtail** [databrickslabs/tempo#277]
Let's say I have two tables, trades and quotes. Trades have three columns, timestamp, stock symbol and price. Quotes also have three columns, timestamp, stock symbol and price.

In this case I understand what happens when you make stock symbol as the partition column in your asof join. You would make two TSDFs both with partition col set to stock symbol.

However for each stock symbol there can be a lot of data. Can I use the timestamp itself as the partition col? Doesn't seem to work.

**Comment by rportilla-databricks** [comment]
Hi @marsupialtail, good question. There is actually an argument to handle cases for skew (e.g. SPY as a large symbol to process). In this case, you can use the tsPartitionVal parameter (set this to an amount of time that you want to create time slices for). The way this works is that we will create a new partition column (ts_partition) which has all records from the existing partition as well as data from the prior partition (with overlap defined by fraction). 

Please try this out and let me know how the performance is. The caveat here is that you may miss prevailing records which fall outside the overlap window. So in cases where the data is sparse (non-SPY-like symbols, we recommend the usual AS OF join).

**Comment by marsupialtail** [comment]
The caveat here is that you may miss prevailing records which fall outside the overlap window. 

I see I presume you do something like a double-join, like in Two Sigma's Flint? 

So the problem is you don't know how many to bins to join against? Thus the overlap fraction parameter?

I don't really understand that parameter -- would appreciate an explanation.

**Comment by rportilla-databricks** [comment]
Correct! I would say this is a salting pattern, wherein we duplicate a small portion of data into each partition (from the previous partition) so that the prevailing records are found. The purpose of the overlap fraction parameter is really to figure out how much of the previous partition we should look at. (0 to 100%)

**Comment by marsupialtail** [comment]
OK. But if my record falls outside of the previous partition then there is no chance at all it gets matched? @rportilla-databricks

**Comment by rportilla-databricks** [comment]
Hi @marsupialtail , this is correct. And for this reason, I would use the skew join (specifying tsPartitionVal, fraction) only for high volume data where there are records expecting in the prior partition. For symbols which don't have large data, you can use the standard AS OF join.

**Comment by marsupialtail** [comment]
Hmmm. I suppose this means that this library can only process minute level data or beyond then. I don't think it would be suitable for tick level data especially for things like SPY.

**Comment by rportilla-databricks** [comment]
That's correct, and I think what you propose is a great suggestion. We will try to incorporate this into tempo. In the meantime, I would be interested in seeing if the standard AS OF join performs well. The skew version is helpful in extreme scenarios but we have found the existing version is optimized well enough too! Let me know.
