### ISSUE TITLE
Difference between ceil, max / floor, min

### ISSUE THREAD

**Issue by TorSy** [databrickslabs/tempo#281]
The documentation does not state how the "func" parameters' different methods actually affect the resampling/interpolation. Mean is obvious, but the difference between ceil and max or floor or min is not clear to me.

For context: I'm working a case with IoT data where sensors can switch within milliseconds. The FFILL is the relevant fill parameter, but I need to ensure the procedure will use the latest (in time) data point for forward filling, within each sampling window (10 sec in my case)

**Comment by rportilla-databricks** [comment]
Thanks for the feedback @TorSy . The point corresponding to the latest point by time would be the func=ceil. I created a PR to update the documentation.

**Comment by rportilla-databricks** [comment]
@TorSy , we merged a PR to address this (#285 ). Let me know if this clears it up.

**Comment by TorSy** [comment]
Thanks for the documentation update. This clears it up! Many thanks.
