### ISSUE TITLE
comparison with Flint

### ISSUE THREAD

**Issue by geoHeil** [databrickslabs/tempo#61]
I am aware of flint (https://github.com/twosigma/flint) and the internal optimizations for time-series (how the data is laid out in memory). How does tempo compare to Flint? Is a similar restructuring performed to allow for fast temporal operations? Or do you solely rely on DeltaLkae partitioning & z-ordering?

**Comment by rportilla-databricks** [comment]
@geoHeil thanks for your question. The tempo project currently does not re-optimize data on disk but we do recommend using the Delta write API and using Delta Lake in general for performance benefits. We Delta adds bucketing, we will use these features under the hood. However, right now with the latest tempo commit, tempo is 2.3X faster than Flint for AS OF joins on 6 months of tick data (using Delta Lake as the storage). If you have further questions please let me know.

**Comment by geoHeil** [comment]
Great to hear that! Thanks for the reply.
But this is not so much a specific hand-optimized AS OF operator in tempo but rather the more and more improved catalyst & SQL layer of spark right?

**Comment by rportilla-databricks** [comment]
It is due to three things: 

1) The hand-optimized AS OF operator optimizes the standard join
2) We don't reorganize data on disk prior to the AS OF join - this happens every time on an ephemeral cluster with Flint (assuming you sort the data which is a performance benefit of Flint) 
3) Catalyst (which you mentioned)

**Comment by geoHeil** [comment]
great. Many thanks for the overview.
