### ISSUE TITLE
Clean up python logging

### ISSUE THREAD

**Issue by tnixon** [databrickslabs/tempo#86]
Hi there, just chiming-in as an end-user:
After this change, we can see the warnings log as follow in databricks:
```
WARNING:root:Column _c had no values within the lookback window. Consider using a larger window to avoid missing values. If this is the first record in the data frame, this warning can be ignored.
```
Note the "root" here.

https://docs.python.org/3.9/howto/logging.html#advanced-logging-tutorial
Based on my own experience, instead of log every line directly using `logging.info`, using a module level logger is preferred, such as:
```
logger = logging.getLogger(__name__)
```
Then the log lines will be more clear, and say sth like `WARNING:tempo.tsdf`, and user can also set logging level in their code, e.g.
```
import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger("py4j").setLevel(logging.WARNING)
logging.getLogger("tempo").setLevel(logging.WARNING)
```

_Originally posted by @CTCC1 in https://github.com/databrickslabs/tempo/issues/83#issuecomment-940457950_

**Comment by rportilla-databricks** [comment]
Update already merged in.
